apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: socket-server
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      containers:
      - name: socket-server-container
        image: senaarth/python-socket-server 
        ports:
        - containerPort: 5001
        - containerPort: 5002
          protocol: UDP
        - containerPort: 5003
        env:
        - name: ENV_VAR_EXAMPLE  # Caso precise de variáveis de ambiente
          value: "example"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: socket-server
  ports:
    - name: tcp-port-5001 
      protocol: TCP
      port: 5001
      targetPort: 5001
    - name: udp-port-5002
      protocol: UDP
      port: 5002
      targetPort: 5002
    - name: tcp-port-5003
      protocol: TCP
      port: 5003
      targetPort: 5003
  type: LoadBalancer  # local usar nodeport
