apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.15.1
  count: 1
  elasticsearchRef:
    name: database
  http:
    service:
        spec:
            type: LoadBalancer