apiVersion: apps/v1
kind: Deployment
metadata:
  name: jogodavida-mpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jogodavida-mpi 
  template:
    metadata:
      labels:
        app: jogodavida-mpi
    spec:
      containers:
        - name: mpi-container
          image: gcr.io/massive-hub-431500-n1/jogodavida-mpi
          imagePullPolicy: Always
          ports:
          - containerPort: 30004
          command: ["mpirun", "-np", "4", "/app/jogo_da_vida_mpi"]
          resources: # Recursos de CPU e memória para o container
            requests:
              cpu: "300m"    # Requisição de 300 milicores, equivalente a 30% de 1 núcleo de CPU
              memory: "128Mi"  # 128 MiB de memória
            limits:
              cpu: "300m"    # Limite de 300 milicores, equivalente a 30% de 1 núcleo de CPU
              memory: "1024Mi"  # Limite de 1024Mi MiB de memória
---
apiVersion: v1
kind: Service
metadata:
  name: jogodavida-mpi
spec:
  selector:
    app: jogodavida-mpi
  ports:
    - name: tcp-port-30004  # Porta TCP
      protocol: TCP
      port: 30004
      targetPort: 30004
      nodePort: 30004
  type: LoadBalancer
